# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sushi Near Me U.S.
publisher: Sushi Near Me U.S.
email: sushinearme.us@gmail.com
logo: /assets/images/sushi_icon.png
logo_icon: icons/sushi_icon.svg
place_focus: sushi
place_type: Sushi Restaurant # used in liquid as singular or plural i.e. steakhouse(s)
description: >- # this means to ignore newlines until "baseurl:"
  Find the best sushi restaurants near you with Sushi-Near-Me.us, your ultimate directory for sushi spots across the US. Explore top-rated sushi bars, local favorites, and hidden gems in every state. Search by location, browse menus, and satisfy your sushi cravings today!
baseurl: '' # the subpath of your site, e.g. /blog
domain: 'Sushi-near-me.us'
url: 'https://www.sushi-near-me.us' # the site's hostname & protocol, e.g. http://example.com
google_analytics: 'G-9Q8C2EW976'
google_site_verification: kWh0myIj2h7tZzeAhHqsZF-Z8CzdZh8Cnp79KIDjwd8

# Build settings
# theme:
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-seo-tag:
  defaults:
    og:type: website

header_pages:
  - index.html
  - search.html
  - about.md
  - contact.html

keywords:
  - sushi near me
  - sushi restaurants
  - sushi close to me
  - best sushi near me
  - sushi restaurants near me
  - japanese places near me
  - sushi places near me
  - I love sushi
  - top rated sushi

social:
#   twitter_username: jekyllrb
#   github_username: jekyll

collections:
  states:
    output: true
  cities:
    output: true
  places:
    output: true

exclude:
  - gemfiles/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - _backend/
  - README.md
  - package.json
  - package-lock.json
  - eslint.config.js
  - CNAME
